"""ScriptedRunner — a deterministic agent backend for offline development.

It walks a task through the same taskboard calls a real agent would make
(plan → progress → artifact → complete), so the whole seam — router, engine,
events, notifier, dashboard — is exercisable and testable with no API key and
no network. The report it writes is clearly labelled as scripted output so it
is never mistaken for real research.
"""

from __future__ import annotations

from .base import AgentRunner, RunResult
from .taskboard import Taskboard


def _build_report(task: dict) -> str:
    spec = task.get("spec") or {}
    goal = spec.get("goal") or task["title"]
    constraints = spec.get("constraints") or []
    lines = [
        f"# {task['title']}",
        "",
        "> Generated by the **scripted runner** (offline mode). This is a",
        "> placeholder that exercises the pipeline end-to-end — not real research.",
        "",
        f"**Goal:** {goal}",
        "",
    ]
    if constraints:
        lines.append("**Constraints considered:**")
        lines += [f"- {c}" for c in constraints]
        lines.append("")
    lines += [
        "## Shortlist (illustrative)",
        "1. **example-org/friendly-tool** — beginner-friendly issues, active maintainers.",
        "2. **example-org/handy-lib** — clear CONTRIBUTING, good first issues labelled.",
        "3. **example-org/small-cli** — small surface area, responsive reviews.",
        "",
        "## Recommendation",
        "example-org/friendly-tool is the strongest match: it has good-first-issue",
        "labels, a one-command dev setup, and maintainers who merge within days.",
    ]
    return "\n".join(lines)


class ScriptedRunner(AgentRunner):
    name = "scripted"

    def __init__(self, taskboard: Taskboard) -> None:
        self.tb = taskboard

    async def run(self, task: dict) -> RunResult:
        tid = task["id"]
        spec = task.get("spec") or {}
        goal = spec.get("goal") or task["title"]

        await self.tb.plan(tid, [
            "understand the request",
            "search for candidates",
            "evaluate contribution-readiness",
            "write the report",
        ])
        await self.tb.report_progress(tid, f"Interpreting: {goal}", step="understand")
        await self.tb.report_progress(tid, "Searching for candidate projects", step="search")
        await self.tb.report_progress(
            tid, "Shortlisted 3 candidates; checking issue hygiene and activity",
            step="evaluate",
        )

        report = _build_report(task)
        summary = (
            "I found three good matches; the strongest has beginner-friendly issues, "
            "active maintainers, and a one-command dev setup. Want me to clone it and "
            "prepare the environment?"
        )
        await self.tb.complete(tid, spoken_summary=summary, report=report)
        return RunResult(ok=True, session_id=None, cost_usd=0.0)
